services:
    aish:
      build:
        context: .
        dockerfile: Dockerfile
      stdin_open: true
      tty: true
      environment:
        - HOME=/mnt/root
        - MODEL_SERVICE_HOST=http://host.docker.internal:11434
        - MODEL_NAME=qwen2.5-coder:32b
        # - MODEL_SERVICE_HOST=https://api.lambdalabs.com/v1
        # - MODEL_NAME=qwen25-coder-32b-instruct # or lfm-40b
        # MODEL_SERVICE_API_KEY=<API-KEY>
      user: root
      volumes:
        - "${PWD}/root:/mnt/root"